CREATE TABLE `USERS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(64) NOT NULL,
    `PASSWORD` VARCHAR(64) NOT NULL,
    `EMAIL` VARCHAR(128) NOT NULL,
    `ENABLED` BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AUTHORITIES`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER` BIGINT NOT NULL,
    `AUTHORITY` VARCHAR(16) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `INFORMATION`
(
    `ID` BIGINT NOT NULL,
	`COUNTRY` VARCHAR(64),
	`ORGANIZATION` VARCHAR(128),
    `HIDE_PUBLIC_OWNED` BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TOKENS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER` BIGINT NOT NULL,
    `TOKEN` VARCHAR(64),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `FILES`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(64) NOT NULL,
    `TYPE` VARCHAR(8) NOT NULL,
    `OWNER` BIGINT NOT NULL,
    `PUBLIC` BOOLEAN NOT NULL,
    `SIZE` BIGINT NOT NULL,
    `BLOCKED` BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (OWNER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SPECIFICATIONS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `PARENT` BIGINT NOT NULL,
    `CHILD` BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PARENT) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (CHILD) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TASKS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `OWNER` BIGINT NOT NULL,
    `MODEL` BIGINT NOT NULL,
    `PROPERTY` BIGINT NOT NULL,
    `RESULT` BIGINT NOT NULL,
    `TYPE` VARCHAR(32) NOT NULL,
    `ACTIVE` BOOLEAN NOT NULL,
    `PROGRESS` VARCHAR(8) NOT NULL,
    `ERROR` TEXT,
    `INFORMATION` TEXT,
     PRIMARY KEY (ID),
     FOREIGN KEY (OWNER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
     FOREIGN KEY (MODEL) REFERENCES FILES(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
     FOREIGN KEY (PROPERTY) REFERENCES FILES(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
     FOREIGN KEY (RESULT) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
