CREATE TABLE `TASKS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `OWNER` BIGINT NOT NULL,
    `MODEL` BIGINT NOT NULL,
    `PROPERTY` BIGINT NOT NULL,
    `RESULT` BIGINT NOT NULL,
    `TYPE` VARCHAR(32) NOT NULL,
    `FINISHED` BOOLEAN NOT NULL,
    `ACTIVE` BOOLEAN NOT NULL,
    `PROGRESS` TEXT,
    `ERROR` TEXT,
    `INFORMATION` TEXT,
    `COMMAND` TEXT,
    `DATE` DATETIME,
     PRIMARY KEY (ID),
     FOREIGN KEY (OWNER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
     FOREIGN KEY (MODEL) REFERENCES FILES(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
     FOREIGN KEY (PROPERTY) REFERENCES FILES(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
     FOREIGN KEY (RESULT) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TASK_DBS`
(
     `ID` BIGINT NOT NULL AUTO_INCREMENT,
     `TASK` BIGINT NOT NULL,
     `SQLITEDB` BIGINT NOT NULL,
     PRIMARY KEY(ID),
     FOREIGN KEY(TASK) REFERENCES TASKS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
     FOREIGN KEY(SQLITEDB) REFERENCES FILES(ID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TASK_FILTERS`
(
     `ID` BIGINT NOT NULL AUTO_INCREMENT,
     `TASK` BIGINT NOT NULL,
     `FILTER` BIGINT NOT NULL,
     PRIMARY KEY(ID),
     FOREIGN KEY(TASK) REFERENCES TASKS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
     FOREIGN KEY(FILTER) REFERENCES FILES(ID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
