CREATE TABLE `USERS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(64) NOT NULL,
    `PASSWORD` VARCHAR(64) NOT NULL,
    `EMAIL` VARCHAR(128) NOT NULL,
    `ENABLED` BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AUTHORITIES`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER` BIGINT NOT NULL,
    `AUTHORITY` VARCHAR(16) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TOKENS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER` BIGINT NOT NULL,
    `TOKEN` VARCHAR(64),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `FILES`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(64) NOT NULL,
    `TYPE` VARCHAR(8) NOT NULL,
    `OWNER` BIGINT NOT NULL,
    `PUBLIC` BOOLEAN NOT NULL,
    `SIZE` BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (OWNER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SPECIFICATIONS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `PARENT` BIGINT NOT NULL,
    `CHILD` BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PARENT) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (CHILD) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, ENABLED)
VALUES ('Jooji', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'Jooji.Kolcak@Gmail.com', TRUE);

INSERT INTO AUTHORITIES (USER, AUTHORITY)
VALUES (1, 'administrator');

INSERT INTO FILES (NAME, TYPE, OWNER, PUBLIC, SIZE)
VALUES ('example', 'dbm', 1, TRUE, 726);

INSERT INTO FILES (NAME, TYPE, OWNER, PUBLIC, SIZE)
VALUES ('example', 'sqlite', 1, TRUE, 13312);

INSERT INTO FILES (NAME, TYPE, OWNER, PUBLIC, SIZE)
VALUES ('test', 'dbm', 1, FALSE, 993);

INSERT INTO FILES (NAME, TYPE, OWNER, PUBLIC, SIZE)
VALUES ('test', 'sqlite', 1, FALSE, 18432);

INSERT INTO SPECIFICATIONS (PARENT, CHILD)
VALUES (1, 2);

INSERT INTO SPECIFICATIONS (PARENT, CHILD)
VALUES (3, 4);