CREATE TABLE `USERS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(64) NOT NULL,
    `PASSWORD` VARCHAR(64) NOT NULL,
    `ENABLED` BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AUTHORITIES`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER` BIGINT NOT NULL,
    `AUTHORITY` VARCHAR(16) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `FILES`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(64) NOT NULL,
    `TYPE` VARCHAR(8) NOT NULL,
    `OWNER` BIGINT NOT NULL,
    `PUBLIC` BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (OWNER) REFERENCES USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SPECIFICATIONS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `PARENT` BIGINT NOT NULL,
    `CHILD` BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PARENT) REFERENCES FILES(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (CHILD) REFERENCES FILES(ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
VALUES ('admin', 'admin', TRUE);

INSERT INTO AUTHORITIES (USER, AUTHORITY)
VALUES (1, 'administrator');

insert into FILES (name, type, owner, public)
VALUES ('example', 'dbm', 1, TRUE);