<%@page contentType="text/html" pageEncoding="UTF-8"%>

<h7>Ooops!</h7>

<div class="info">
    <p>
        Files of the type ".${type}" cannot be opened!
    </p>
    <p>
        We are terribly sorry for the inconvenience caused.<br/>
        Your satisfaction is our highest priority and that is why we are constantly striving to make Esther better.
        If your ".${type}" file was generated by Esther the support for ".${type}"
        should be coming soon so please have a cookie in the meantime.<br/>
        (>'_')>O
    </p>
</div>
